---
name: Java-Makefile
distribution_type:  module
abstract: 'Script to generate Makefile for building Java projects into a single standalone jar'
author:
  - 'David Helkowski <cpan@codechild.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: mixed; cc-by-sa 4.0 and epl 1.0
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
requires:
  XML::Bare: 0.53
version: 1.00
